// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_wkHB-ha08tkyQy1wclp55v1xyyxIP0',
    appId: '1:168378474618:web:ba26383ce9ea63dbecdbc3',
    messagingSenderId: '168378474618',
    projectId: 'pix-app-8160e',
    authDomain: 'pix-app-8160e.firebaseapp.com',
    storageBucket: 'pix-app-8160e.firebasestorage.app',
    measurementId: 'G-T9V38FE201',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJMrIiuAltlPn13vl6bylEF0s1bFH2MoE',
    appId: '1:168378474618:android:4b4a6061de36d118ecdbc3',
    messagingSenderId: '168378474618',
    projectId: 'pix-app-8160e',
    storageBucket: 'pix-app-8160e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdd5pvQHuzbrmATn_POYzkzCT_cTFy2zk',
    appId: '1:168378474618:ios:bdf526e1f290e99aecdbc3',
    messagingSenderId: '168378474618',
    projectId: 'pix-app-8160e',
    storageBucket: 'pix-app-8160e.firebasestorage.app',
    iosBundleId: 'com.legendsumeet.picpixels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdd5pvQHuzbrmATn_POYzkzCT_cTFy2zk',
    appId: '1:168378474618:ios:bdf526e1f290e99aecdbc3',
    messagingSenderId: '168378474618',
    projectId: 'pix-app-8160e',
    storageBucket: 'pix-app-8160e.firebasestorage.app',
    iosBundleId: 'com.legendsumeet.picpixels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_wkHB-ha08tkyQy1wclp55v1xyyxIP0',
    appId: '1:168378474618:web:928f5d11c78c6a15ecdbc3',
    messagingSenderId: '168378474618',
    projectId: 'pix-app-8160e',
    authDomain: 'pix-app-8160e.firebaseapp.com',
    storageBucket: 'pix-app-8160e.firebasestorage.app',
    measurementId: 'G-PNR1XZ4KWM',
  );

}
